### ISSUE TITLE
Switch to Connexion framework

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#10]
Use Connexion for REST API implementation, using the Swagger API spec to define the functionality

**Comment by tvirolai** [comment]
Note to self: here's how the Flask -> Connexion switch works without breaking existing functionality (ie. command-line interface implemented with Click).

First, create the Connexion app:
`annif = connexion.App(__name__) `

The Connexion app wraps a normal Flask app, which is here `annif.app`.

Then define the functions and map them to command-line commands like this:

`@annif.app.cli.command('show-project')
@click.argument('projectid')
def show_project(projectid):
    asdflkjsdf`

Lastly, add the Swagger API:

`annif.add_api('api.yaml')`

I'll try to get this implemented right away.
