### ISSUE TITLE
Home.html not found

### ISSUE THREAD

**Issue by hekl** [NatLibFi/Annif#221]
I did a basic install of annif and it works on the command line, but when I start the webserver and go to http://127.0.0.1:5000/  I get this error:
`jinja2.exceptions.TemplateNotFound: home.html`

I don't see any directory with templates. Adding it with the files to the top folder didn't help.

**Comment by osma** [comment]
Thanks for the report. Probably the package build is missing the templates directory. I'll take a look!

**Comment by osma** [comment]
There is now version 0.37.2 on PyPI where this issue should be fixed. Please reopen if you still see the same problem!

**Comment by hekl** [comment]
I will try it out, thanks.
