### ISSUE TITLE
Character encoding (Windows)

### ISSUE THREAD

**Issue by Veldhoen** [NatLibFi/Annif#262]
Python uses default system character encoding in calls to open(..). Under my Windows installation, this is cp1252, causing 'annif loadvoc' to fail with encoding errors. 
I created a pull request where I explicitly added the encoding (utf-8) in every call to open(..)

**Comment by osma** [comment]
Thanks for the issue report and the PR! Will look into this. I've only used Annif on Linux (using a UTF-8 locale) so haven't encountered this problem so far...
