### ISSUE TITLE
Auto-generate API documentation

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#277]
For users and especially developers getting familiar with the Annif codebase, it would help a lot to set up browsable API documentation generated using e.g. Sphinx. It could then be published on ReadTheDocs.

**Comment by osma** [comment]
[This PyCon 2018 talk](https://www.youtube.com/watch?v=0ROZRNZkPS8) by Carol Willing seems like a good introduction to the subject

Note that at this stage we would still keep the non-API documentation in the GitHub wiki.

**Comment by osma** [comment]
Another tutorial that looks good https://samnicholls.net/2016/06/15/how-to-sphinx-readthedocs/

**Comment by kinow** [comment]
+1

We generate the API documentation with Sphinx, though not using readthedocs, but instead a github pages site. Then the generated API is included in the manual part of the site as a per-section doc, and as a single page. For that, we had to customize the setuptools integration [a bit](https://github.com/cylc/cylc-flow/blob/924c91bee9371dad805a0c7b9b4965b111580b70/setup.py#L54-L101).

But the hard work had been done some time ago in putting a theme and structure in a [`conf.py`](https://github.com/cylc/cylc-flow/blob/924c91bee9371dad805a0c7b9b4965b111580b70/doc/src/conf.py) settings file.
