### ISSUE TITLE
Dockerize Annif

### ISSUE THREAD

**Issue by juhoinkinen** [NatLibFi/Annif#278]
Make docker image containing Annif, upload to e.g. Dockerhub or Portainer (private repository).

**Comment by osma** [comment]
I think this is done now and the issue can be closed? @juhoinkinen ?
Do we still need to add documentation somewhere, or improve the way images are built and/or distributed?

**Comment by juhoinkinen** [comment]
I added the [Usage with Docker](https://github.com/NatLibFi/Annif/wiki/Usage-with-Docker) page to the TOC of Wiki. 

Also added a section on creating&using the data image: https://github.com/NatLibFi/Annif/wiki/Usage-with-Docker#using-annif-with-gunicorn-nginx-and-maui-backend

Closing this now.
