### ISSUE TITLE
Validate TSV training input

### ISSUE THREAD

**Issue by annakasprzik** [NatLibFi/Annif#281]
Maybe Annif could check the input tsv files for trivial flaws such as excessive newlines not containing any tab character and give out a warning. Right now you receive an error from some Python method instead which might not be very transparent for users that are not proficient in Python (and even for those who are).

**Comment by osma** [comment]
Indeed, the TSV parser should be more robust.

See [related discussion](https://groups.google.com/forum/#!topic/annif-users/b0MvpU-wXm4) on annif-users. Here the issue was an empty line which caused an ugly error.
