### ISSUE TITLE
Allow Custom Maui Configuration in mauiservice Docker Container

### ISSUE THREAD

**Issue by mo-fu** [NatLibFi/Annif#301]
When trying out the maui backend, I found out that it is not documented how to run the mauiservice container with a custom configuration. I had to work around this in two ways:

1. Name the files like in the example
2. Start the container interactively and either use sed or install an editor to change the mauiservice file

Since it is a requirement to mount a volume for the model, it would be great if the mauiservice.ini could be stored in the mounted directory.

Hopefully I filled this report in the correct place, as I could not find the mauiservice dockerfile in this repository or the mauiservice one.

**Comment by TommiRTVA** [comment]
This is needed indeed. Good workaround :) How did you manage to reload application to use the modified ini-file without restarting container?

**Comment by TommiRTVA** [comment]
Simple _docker reload [docker-name]_ was enoungh.

**Comment by mo-fu** [comment]
@TommiRTVA I just ran `catalia.sh run` while still inside the container. I think your solution is better, as you don't have to change the file again when you want to do another experiment.

**Comment by juhoinkinen** [comment]
Yes, this definitely is needed, thanks for reporting!

I added an env to the [`docker-compose.yml`](https://github.com/NatLibFi/Annif/blob/master/docker-compose.yml#L21) that explicitly sets the path to the Mauiservice config file and instructions on [wiki page](https://github.com/NatLibFi/Annif/wiki/Usage-with-Docker/_edit#using-annif-with-gunicorn-nginx-and-maui-backend) about changing the path. 

Also, added instructions for setting the path in the case of [single container](https://github.com/NatLibFi/Annif/wiki/Backend%3A-Maui/_edit#usage-with-docker). 

Hope this solved the issue for you, please comment if there there are still any issues!
