### ISSUE TITLE
Problems with UTF-8 BOM -encoded documents when using eval-command

### ISSUE THREAD

**Issue by TommiRTVA** [NatLibFi/Annif#307]
If documents used in training are in UTF-8 BOM -format, there are issues when using eval-command. It adds whitespace in front of the first line in every document evaluated.

As result, every documents first line is rejected as "unknown subject label".

This does not happen when documents are in UTF-8 format without BOM.

annif_user@7329a5134b0f:/annif-projects$ annif eval tfidf-debug /annif-projects/Annif-corpora/fulltext/tekstitykset/maui-train/
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p9142>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p67>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p10409>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p27030>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p2434>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p8394>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p2382>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p5878>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p15103>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p13084>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p15401>"
warning: Unknown subject label "﻿<http://www.yso.fi/onto/yso/p15501>"

**Comment by osma** [comment]
The TSV parser should ignore/skip the BOM.

**Comment by osma** [comment]
I think we need to solve this soon, otherwise there will be problems in the Annif tutorial.

Probably all it takes is to change the encoding from `utf-8` to `utf-8-sig` when reading files. See this SO question and the top answers:
https://stackoverflow.com/questions/13590749/reading-unicode-file-data-with-bom-chars-in-python
