### ISSUE TITLE
Wiki: Error in the example config (HTTP Backend)

### ISSUE THREAD

**Issue by niko2342** [NatLibFi/Annif#337]
There is a small error in the example config for the [HTTP backend](https://github.com/NatLibFi/Annif/wiki/Backend%3A-HTTP). The config option should be _backend_ and not _backends_.

```diff
[http-en]
name=HTTP English
language=en
-backends=http
+backend=http
endpoint=http://localhost:5050/yso-en/suggest
vocab=yso-en

**Comment by osma** [comment]
Thanks, good catch! This has now been fixed.

Note that anyone can edit wiki pages, so you can perform simple corrections like this also by yourself!
