### ISSUE TITLE
Epoch-parameter for nn_ensemble learn-command

### ISSUE THREAD

**Issue by TommiRTVA** [NatLibFi/Annif#355]
Maybe it would be useful to add epoch-parameter to the nn_ensemble learn-command. This could be used, if there is lot of data for learn-command, 1000 documents or more.

Default value would be 1 like now, because when there is only one or few additional data to learn, additional learning cycles would likely cause only harm.

**Comment by osma** [comment]
This would be useful. I think the easiest way would be to add a new parameter `learn-epochs`, which would default to 1, but it would be possible to set either in `projects.cfg` or on the command line, like this:

    annif learn -b my-nn-ensemble.learn-epochs=10 my-nn-ensemble training-data/

This would require implementing #250 first, so the `-b` / `--backend-param` can be used also with the `train` and `learn` commands. We have an open PR about it (#289) but it's a bit stale and should be updated.

Does that sound reasonable?

**Comment by TommiRTVA** [comment]
Yes , good to have consistency with commands. Thanks!

**Comment by osma** [comment]
The `learn-epochs` parameter has now been added to the `master` branch and will be in the next release (0.44).

It has to be set in `projects.cfg` though, the `-b` option is not (yet) implemented for `train` and `learn` CLI commands (see #250)
