### ISSUE TITLE
Remove vw_ensemble backend

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#362]
I'd like to remove the `vw_ensemble` backend. The neural network ensemble (`nn_ensemble`) has essentially the same features (e.g. incremental learning) and works much better. It doesn't make sense to maintain two backends for the same purpose and it would take a significant amount of work to get good quality results from `vw_ensemble`, if it's even possible.

**Comment by juhoinkinen** [comment]
I added a note in the [Wikipage](https://github.com/NatLibFi/Annif/wiki/Backend:-vw_ensemble) about removing the backend. Did not dare to yet delete it altogether.
