### ISSUE TITLE
Annif breaks when MauiServer returns malformed URIs for topic IDs

### ISSUE THREAD

**Issue by mjsuhonos** [NatLibFi/Annif#389]
### Steps to reproduce

```
annif loadvoc rula-maui-en Annif-corpora/vocab/lcsh/lcsh.ttl
annif train rula-maui-en Annif-corpora/fulltext/rula/validate/
```
https://github.com/mjsuhonos/Annif-corpora/blob/master/vocab/lcsh/lcsh.ttl
https://github.com/mjsuhonos/Annif-corpora/tree/master/fulltext/rula/validate

```
annif eval rula-maui-en Annif-corpora/fulltext/rula/test/ -v DEBUG
```
```python

…

warning: Unknown subject URI <http://id.loc.gov/authorities/subjects/http://id.loc.gov/authorities/genreForms/gf2011026450>
Traceback (most recent call last):
  File "/usr/local/bin/annif", line 11, in <module>
    load_entry_point('annif', 'console_scripts', 'annif')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Annif/annif/cli.py", line 305, in run_eval
    results = project.suggest(doc.text, backend_params)
  File "/Annif/annif/project.py", line 161, in suggest
    hits = self._suggest_with_backend(text, backend_params)
  File "/Annif/annif/project.py", line 105, in _suggest_with_backend
    hits = self.backend.suggest(text, beparams)
  File "/Annif/annif/backend/backend.py", line 67, in suggest
    return self._suggest(text, params=beparams)
  File "/Annif/annif/backend/maui.py", line 155, in _suggest
    return self._response_to_result(response)
  File "/Annif/annif/backend/maui.py", line 150, in _response_to_result
    self.project.subjects)
  File "/Annif/annif/suggestion.py", line 169, in create_from_index
    subject = subject_index[subject_index.by_uri(hit.uri)]
  File "/Annif/annif/corpus/subject.py", line 55, in __getitem__
    return (self._uris[subject_id], self._labels[subject_id],
TypeError: list indices must be integers or slices, not NoneType
```

### Malformed response

Document source (1126 bytes)

> Key findings:  The survey results for both countries were similar in terms of the percentage of respondents who reported working
 in smaller newsrooms and working longer hours compared to two years ago  Respondents in both countries said that the perception
  of local newspapers as a dying industry deters advertisers and makes it challenging to recruit new staff  Use of metrics to
   measure engagement and shape the production of stories is about the same in both countries  Respondents in Canada and the
    United States both reported that few employers provided training courses to assist with learning about new technologies 
 While approximately half of the participants in both surveys felt slightly or very secure in their jobs, almost twice as
  many Canadians felt slightly or very insecure in their jobs  American respondents overall tended to be more positive 
  about the future of local newspapers  Respondents from American newspapers were more likely to use video reporting, 
  live video and **and podcasts than their Canadian counterparts Researchers who compare the state of local journalism across** 

```json
{
  "title": "10 recommendations from rula-maui-en",
  "topics": [
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85004368",
      "label": "American newspapers",
      "probability": 0.06058101652075777
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/http://id.loc.gov/authorities/genreForms/gf2011026450",
      "label": "http://id.loc.gov/authorities/subjects/http://id.loc.gov/authorities/genreForms/gf2011026450",
      "probability": 0.03634347847356808
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85143204",
      "label": "Video recordings",
      "probability": 0.02480501693510654
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85070585",
      "label": "Job security",
      "probability": 0.022298487879186563
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh2007001518",
      "label": "Podcasts",
      "probability": 0.021532180099457447
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh2006006472",
      "label": "Podcasting",
      "probability": 0.021532180099457447
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh2012001802",
      "label": "Podcasters",
      "probability": 0.021532180099457447
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85091588",
      "label": "Newspapers",
      "probability": 0.01622784151074123
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh99001641",
      "label": "Newspapers",
      "probability": 0.01622784151074123
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh2007008878",
      "label": "First responders",
      "probability": 0.01622784151074123
    }
  ]
}
```

### Correct response

Document source (1126 bytes)

> Key findings:  The survey results for both countries were similar in terms of the percentage of respondents who reported working
 in smaller newsrooms and working longer hours compared to two years ago  Respondents in both countries said that the perception
  of local newspapers as a dying industry deters advertisers and makes it challenging to recruit new staff  Use of metrics to
   measure engagement and shape the production of stories is about the same in both countries  Respondents in Canada and the
    United States both reported that few employers provided training courses to assist with learning about new technologies 
 While approximately half of the participants in both surveys felt slightly or very secure in their jobs, almost twice as
  many Canadians felt slightly or very insecure in their jobs  American respondents overall tended to be more positive 
  about the future of local newspapers  Respondents from American newspapers were more likely to use video reporting, 
  live video and **common questions revealed two notable differences between the countries. The first had to do with sentiments**

```json
{
  "title": "10 recommendations from rula-maui-en",
  "topics": [
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85004368",
      "label": "American newspapers",
      "probability": 0.06058101652075777
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85143204",
      "label": "Video recordings",
      "probability": 0.02480501693510654
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85070585",
      "label": "Job security",
      "probability": 0.022298487879186563
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85091588",
      "label": "Newspapers",
      "probability": 0.01622784151074123
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh99001641",
      "label": "Newspapers",
      "probability": 0.01622784151074123
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh2007008878",
      "label": "First responders",
      "probability": 0.01622784151074123
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh93009373",
      "label": "Advertisers",
      "probability": 0.01382364849909128
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh85001086",
      "label": "Advertising",
      "probability": 0.01382364849909128
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh2001009077",
      "label": "Supplementary employment",
      "probability": 0.01382364849909128
    },
    {
      "id": "http://id.loc.gov/authorities/subjects/sh2005004875",
      "label": "Employability",
      "probability": 0.01382364849909128
    }
  ]
}
```

### Suspected cause

This vocabulary contains two `skos:prefLabel` statements with identical object literals:
```
<http://id.loc.gov/authorities/genreForms/gf2011026450> <http://www.w3.org/2004/02/skos/core#prefLabel> "Podcasts"@en .
<http://id.loc.gov/authorities/subjects/sh2007001518> <http://www.w3.org/2004/02/skos/core#prefLabel> "Podcasts"@en .
```

It seems plausible that due to its lexical approach, Maui uses the object literal as a unique value, which would match two topic URIs, given the above statements.  The (albeit strangely truncated) concatenation of these two URI values are then returned in the response.

This theory is currently being tested.

### Proposed resolution

Ideally, Annif could extract valid URIs from the invalid response, but this may be too much overhead if each response URI must be validated.

At a minimum, Annif should ignore the malformed response and continue with eg. a warning statement on STDERR.

**Comment by osma** [comment]
Thanks for the bug report. The real problem seems to be in MauiServer. There's not much Annif can do if MauiServer returns clearly invalid URIs (although maybe it shouldn't crash like it apparently does).

I've never seen this problem happen with the data sets I've used - even when vocabularies have contained duplicate prefLabels. Is it possible that this is an issue with the vocabulary data that was given to MauiServer via Annif? Since you trained MauiServer via Annif, you could have a look at the `data/vocabs/<my_vocab_id>/subjects.ttl` file and see if it contains the bad URI.

If that vocabulary file is OK (doesn't contain bad URIs), could you file this as an issue [this MauiServer repo](https://github.com/NatLibFi/MauiServer), which is our fork of the upstream MauiServer. Ideally you could also include a minimal example for how to trigger it (i.e. a small vocabulary and a few training documents).

**Comment by mjsuhonos** [comment]
My apologies, I didn't realize there was a maintained fork of MauiServer.  The issue is definitely there and not with Annif.  I've checked the vocabulary data and it doesn't contain the bad URI shown in the error.  I'll file an issue at the MauiServer repo and cross-link it here once I have an example prepared.

**Comment by osma** [comment]
No worries! I changed the title of this issue to reflect the Annif side robustness problem - that it crashes when MauiServer returns a "surprising" URI. It should warn about the situation but not crash like this.

**Comment by mjsuhonos** [comment]
I've managed to identify the code responsible for this issue in maui (not MauiServer); it appears this is intentional behaviour, ie. when storing a vocabulary, maui assumes that all descriptor URIs share the same prefix.

The relevant code can be seen here:

https://github.com/NatLibFi/maui/blob/master/src/main/java/com/entopix/maui/vocab/VocabularyStore_HT.java#L38-L46

While IMO this is a reasonable assumption, it is potentially problematic for cases like LCSH which tend to mix prefixes, eg.
```
http://id.loc.gov/authorities/subjects/
http://id.loc.gov/authorities/genreForms/
http://id.loc.gov/authorities/names/
http://id.loc.gov/authorities/performanceMediums/
```
It also causes problems when using URNs, as in my case for local subject URIs.

I'm afraid I'm not competent enough with Java to suggest an alternative implementation, and the NatLibFi/maui repo currently doesn't allow submitting of issues, only pull requests.

From the perspective of Annif, the only workaround I can think of is to use multiple vocabularies, partitioned by URI prefix.  I'm willing to modify my data to take this approach, but I'm unsure how to eg. use multiple TSV files for different subject vocabularies on the same source document.

The only other idea I have is to mint a pile of "local" URIs which share a common prefix, but can be used to redirect / assert rdf:sameAs to the actual "real" URIs outside of the application, eg.

```
http://some.local.prefix/subjects-1234 --> http://id.loc.gov/authorities/subjects/1234
http://some.local.prefix/names-1234 --> http://id.loc.gov/authorities/names/1234
http://some.local.prefix/y42LW46J9luq3Xq9XMly --> urn:rula:y42LW46J9luq3Xq9XMly
```

Thoughts welcome.

**Comment by osma** [comment]
Thanks for the analysis @mjsuhonos !

> I'm afraid I'm not competent enough with Java to suggest an alternative implementation, and the NatLibFi/maui repo currently doesn't allow submitting of issues, only pull requests.

Oh, didn't realize that. I've now enabled Issues for the repo.

I think both of your suggested workarounds are not ideal, for various reasons. The assumption of all concept URIs sharing the same prefix seems unnecessary and I don't think it would be difficult to fix that. In fact, when I look at the code, I think it's simply buggy: the createIDFromURI method seems to handle the case where the prefix of an incoming URI doesn't match the assumed prefix (taken from the first URI it encountered), but the createURIFromID method forgets about this case. Extracting the shared prefix is done simply to save disk space / RAM, but it looks like a case of premature optimization gone wrong...

This will bite us as well sooner or later (for example we are using URNs too) so it would be better to fix it in Maui code. Please open the issue there and I'll see what I can do.

**Comment by mjsuhonos** [comment]
This is now submitted as [an issue in maui](https://github.com/NatLibFi/maui/issues/5).  Thanks @osma!

**Comment by osma** [comment]
Thanks MJ. The Annif side robustness issue is now fixed on the `master` branch.

**Comment by mjsuhonos** [comment]
Training the maui backend ("rula-maui-en") now silently ignores these errors coming back from MauiServer, great!

Unfortunately, when I wrap the maui backend in an nn_ensemble ("rula-maui-ensemble-en"), the same error appears as reported above.  The testing configuration in this case is:

```
[rula-maui-en]
name=RULA IR Maui project
language=en
backend=maui
vocab=lcsh
endpoint=http://mauiserver:8080/mauiserver/
tagger=rula-maui-en

[rula-maui-ensemble-en]
name=RULA Maui Ensemble English
language=en
backend=nn_ensemble
sources=rula-maui-en
limit=100
nodes=100
dropout_rate=0.2
epochs=10
vocab=lcsh
```

Any idea why the nn-ensemble would continue to be affected?

Sorry to revive this issue. :persevere:

**Comment by osma** [comment]
Hi @mjsuhonos, did you still have a follow-up problem with the NN ensemble? I got a notification for a comment but can't see the comment itself anymore...did you delete it?

**Comment by mjsuhonos** [comment]
Hi @osma, yes, sorry I realized after posting that it was just the Docker image hasn’t been updated to include the commit, so deleted the comment. All good.

**Comment by osma** [comment]
Okay great! We do have Docker images auto-built from the `master` branch published on quay.io - the `latest` tag follows `master`. https://quay.io/repository/natlibfi/annif?tab=tags

**Comment by juhoinkinen** [comment]
Actually the Docker image auto-build for the fixing branch #402 merge failed due to some network connection problem. I rerun that build now so now the image has the fix.
