### ISSUE TITLE
Evaluation per-subject

### ISSUE THREAD

**Issue by Veldhoen** [NatLibFi/Annif#391]
A model can be evaluated from the perspective of documents (e.g. how many correct terms were suggested for this document?) and from the perspective of subjects (e.g. how often was this subject suggested correctly?). To compute metrics, true and false positives and negatives are counted. For determining micro average, the overall counts are the same for both perspectives, but computing a macro average for documents is different from a macro average for subjects.

I propose two enhancements:
- When reporting the evaluation metrics, specify the interpretation of each metric and add weighted subject average as a metric. 
- Provide an option to output non-aggregated results per subject, to allow for a qualitative evaluation of the model (e.g. a model may be good at suggesting a certain range of topics, whereas it fails on other topics). With non-aggregated results, one can explore the relation between the frequency of subjects in the dataset and corresponding model performance.

**Comment by osma** [comment]
Thanks for the suggestion. Feel free to make PRs. It might be best to make a separate PR for each specific feature if possible.

**Comment by Veldhoen** [comment]
Thanks. I've created separate PRs as you suggested. I am not very familiar with all the OS processes, so chances are I did something suboptimal. Any suggestions are welcome :)

I see that some automated tests failed, I will look into that later this week.

**Comment by osma** [comment]
Thanks for the PRs! I've reviewed them both. #392 looks very good, with only minor whitespace issues. #393 is a bit more complicated, but I've suggested some ways to improve it and fix the test failures.

**Comment by Veldhoen** [comment]
PR #393 just got approved and merged. Closing this issue now.
