### ISSUE TITLE
Maui Server errors are not shown by Annif

### ISSUE THREAD

**Issue by hekl** [NatLibFi/Annif#401]
I have an rdf vocabulary and loaded it for the maui backend. But when I try to train it with txt en tsv file, it gives this error. 

> (annif046) enrico@ubupiet:~/Programs/annif046$ bin/annif train -v DEBUG maui-nl data/annif-corpora/fulltext/train_maui
debug: creating app with configuration annif.default_config.Config
debug: loading subjects from data/vocabs/maui-nl/subjects
Backend maui: Initializing Maui Server tagger 'maui-nl'
debug: Backend maui: Trying to delete tagger maui-nl returned status code 204
debug: Backend maui: Trying to create tagger maui-nl returned status code 200
Backend maui: Uploading vocabulary
Error: Operation failed: 400 Client Error:  for url: http://localhost:8080/mauiserver/maui-nl/vocab

There is a subjects file generated but it does recognize a vocabulary. 

http://localhost:8080/mauiserver/maui-nl
{"title":"maui-nl","id":"maui-nl","is_trained":false,"has_vocabulary":false,"links":{"home":"/mauiserver/","tagger":"/mauiserver/maui-nl","config":"/mauiserver/maui-nl/config","vocab":"/mauiserver/maui-nl/vocab","train":"/mauiserver/maui-nl/train","suggest":"/mauiserver/maui-nl/suggest","xvalidate":"/mauiserver/maui-nl/xvalidate"}}

This is my project setup. 

> [maui-nl]
> name=Maui Dutch
> language=nl
> backend=maui
> endpoint=http://localhost:8080/mauiserver/
> tagger=maui-nl
> vocab=maui-nl
> limit=5

**Comment by osma** [comment]
Can you find any hints in the Maui Server log file?

**Comment by hekl** [comment]
I am using tomcat9. The service status just says:

> NFO RootServlet - GET /maui-nl/vocab/ 404, json: "The resource does not exist"

At  /var/log/tomcat9 there is a tomcat9 locahost acces_log which is updated, and it says:

> 127.0.0.1 - - [31/Mar/2020:13:28:14 +0200] "DELETE /mauiserver/maui-nl HTTP/1.1" 204 -
127.0.0.1 - - [31/Mar/2020:13:28:14 +0200] "POST /mauiserver/ HTTP/1.1" 200 179
127.0.0.1 - - [31/Mar/2020:13:28:15 +0200] "PUT /mauiserver/maui-nl/vocab HTTP/1.1" 400 100

The other two logs there are not updated: a catalina.log and a localhost.log. Is there another log you refer to?

**Comment by osma** [comment]
Clearly the PUT request for /mauiserver/maui-nl/vocab is the problem here. It would be good to get a traceback or some other type of debugging information.

You could try to upload the vocabulary directly to Maui Server using `curl` - perhaps the response would tell you something that gets lost when the upload goes via Annif. See example here: https://github.com/TopQuadrant/MauiServer/blob/master/API.md#put-replace-vocabulary

I'm using tomcat8 on Ubuntu 16.04. The most detailed and relevant log file is /var/log/tomcat8/catalina.2020-03-31.log - do you have anything similar in your tomcat 9?

**Comment by hekl** [comment]
Yes, I have that log too, but it seems to log only the start up. There is an advice to enable logging for org.apache.jasper.servlet.TldScanner.scanJars. I will try your other suggestion.

**Comment by hekl** [comment]
I have tried the direct put statement. 

>  curl -X PUT --data-binary @subjects.ttl http://localhost:8080/mauiserver/maui-nl
{"status":405,"status_text":"Method Not Allowed","message":"HTTP method PUT not supported on this resource","allowed_methods":["GET","HEAD","DELETE"]}

**Comment by osma** [comment]
You used the wrong URL, it should be http://localhost:8080/mauiserver/maui-nl/vocab

**Comment by hekl** [comment]
You are right. I get this error:
{"status":400,"status_text":"Bad Request","message":"No stemmer class registered for language 'nl'"}. Ok. Then with the same api commands I will have to add a configuration. But I see that Dutch is not supported. Then server default null will have  to do. I am actually not keen on a real stemmer, this might introduce noise.

**Comment by osma** [comment]
Ah right. MauiServer only knows about a few stemmers, registered [here](https://github.com/NatLibFi/MauiServer/blob/master/src/main/java/org/topbraid/mauiserver/tagger/TaggerConfiguration.java#L50). Others are available if you configure it separately, as you noted, but not Dutch (the full list of stemmers implemented in Maui is [here](https://github.com/NatLibFi/maui/tree/master/src/main/java/com/entopix/maui/stemmers))

I'll change this issue to reflect the problem that the error message from Maui Server is not shown by Annif. If you had seen the "No stemmer class registered..." message in Annif output, it would have helped a lot.

**Comment by hekl** [comment]
Thanks for your help. There are of course a lot of more stemmers used in Java. For Lucene there are two stemmers for Dutch.

**Comment by osma** [comment]
Right. If you need them with Maui, please open a pull request against https://github.com/NatLibFi/Maui ;)

**Comment by hekl** [comment]
Good idea. Some people will find them handy.

**Comment by hekl** [comment]
In the present configuration the stemmer class is already set to null, so that means that I have to set the language also to null. Or us a default java stemmer.

**Comment by osma** [comment]
FYI, I tested this myself using the same configuration and some junk data and got the same result. I found this in `catalina.log`:

```
01 Apr 2020 08:48:18  INFO RootServlet - PUT /maui-nl/vocab 400, json: "No stemmer class registered for language 'nl'"
```

Working on a fix to show this error also in Annif output.

**Comment by hekl** [comment]
Basically I can't get maui to work with the dutch language at all. The docs of course say that it is limited to a number of languages. So, maybe that should be another request. Setting stemmers or stopwords to null doesn't work, invoking nostemmer brings up an error about a missing stopwords class. There is no "no-stopwords" class. I would like it to work with a basic tokenizer just like annif does.

**Comment by osma** [comment]
@hekl Please open issues against MauiServer then (or Maui)
