### ISSUE TITLE
RAKE-like backend

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#439]
There are many Python implementations and variations of the RAKE algorithm [1] which extracts uncontrolled keywords or keyphrases from text documents. We could integrate one of these as an Annif backend. The idea would be that the keywords suggested by the algorithm would be looked up from the vocabulary (using both prefLabels and altLabels) and the keywords that are found in the vocabulary would be returned as suggestion results. Optionally, the keywords that are outside the vocabulary could be returned as well (see issue #224 where this kind of functionality has been suggested).

Some possible RAKE implementations to choose from:

* https://github.com/fabianvf/python-rake
* https://github.com/vgrabovets/multi_rake
* https://github.com/csurfer/rake-nltk
* https://github.com/LIAAD/yake
* https://github.com/aneesha/RAKE (original, ancient Python implementation)

We need to select one of these. Selection criteria could include:

* quality of results
* multilingual support
* library requirements (is it compatible with Annif requirements?)
* Python version requirements (does it work with the Python versions Annif supports?)
* maintenance status

[1] Rose, S., Engel, D., Cramer, N. and Cowley, W. (2010). Automatic Keyword Extraction from Individual Documents. In Text Mining (eds M.W. Berry and J. Kogan). doi:10.1002/9780470689646.ch1

**Comment by osma** [comment]
Another, more generic option would be [pke - python keyphrase extraction](https://github.com/boudinfl/pke)

**Comment by juhoinkinen** [comment]
A review paper on keyphrase extraction methods including comparison of their results: https://arxiv.org/abs/1905.05044 Most methods were implemented using PKE.
