### ISSUE TITLE
Allow use of cached data after cancelled training of nn_ensemble backend

### ISSUE THREAD

**Issue by mo-fu** [NatLibFi/Annif#443]
When cancelling training of the `nn_ensemble` backend after the data transformation was completed, the backend is not able to use the cached data written to the lmdb file.
A quick fix for me was to disable locking when opening the lmdb file but that opens another can of worms.
Another possible solution could be to close the db after writing all the data and reopening it in readonly mode. Have not tested yet whether this would do the trick.

**Comment by osma** [comment]
Thanks for the suggestion @mo-fu! I haven't encountered that situation personally but I understand it must be frustrating, as the training data preparation can take a very long time with the NN ensemble.

Closing and reopening as read-only sounds like a good idea. Care to test and submit a PR? :)

**Comment by mo-fu** [comment]
Unfortunately I do not have the time right now, as I have to train models. This takes some time, so I want to interfere with the process as little as possible.

**Comment by osma** [comment]
![Obligatory Xkcd](https://imgs.xkcd.com/comics/compiling.png)

**Comment by osma** [comment]
Seems like a quick fix would be quite easy to do, I'll give it a shot
