### ISSUE TITLE
Limit parameter is not passed to MauiServer

### ISSUE THREAD

**Issue by juhoinkinen** [NatLibFi/Annif#459]
Maui backend gives at most 10 suggestions even if a larger `limit` value is set in Annif. 

At training time [only `id` and `lang` parameters are passed to MauiServer](https://github.com/NatLibFi/Annif/blob/98bde2375abe17a6a1d368fd9acae6f2edf09c00/annif/backend/maui.py#L82), and [the default value of 10](https://github.com/NatLibFi/MauiServer/blob/master/src/main/java/org/topbraid/mauiserver/tagger/TaggerConfiguration.java#L36) is always used for `max_topics_per_document`.

```
# http://localhost:8080/mauiserver/tmp-maui-fi/config

id | "tmp-maui-fi"
-- | --
title | "tmp-maui-fi"
description | null
lang | "fi"
stemmer_class | null
stopwords_class | null
cross_validation_passes | 10
max_topics_per_document | 10
probability_threshold | 0
```
 
When Maui backend is used in an ensemble project, getting more suggestions would be advantageous.

**Comment by osma** [comment]
Good catch! This should be relatively easy to fix - just pass the configured `limit` value to Maui as `max_topics_per_document`.

It does mean that the limit used by Maui will be fixed during train time, unlike for other backends where it's applied only during suggest operations. I don't think this is a major problem but could perhaps be noted on the wiki page of the Maui backend.
