### ISSUE TITLE
Language filtering in input text

### ISSUE THREAD

**Issue by juhoinkinen** [NatLibFi/Annif#464]
A model's attempts to process (in training/suggesting) text in a language different to the project's language are disadvantageous. Generally, any text-parts in a "foreign" language in a document probably just act as noise, but when the input-limit parameter (#446 and #452) is used, the drawback can be more serious: some thesis have abstracts in two or even three languages, and when the text is limited to a fixed number of characters, the retained text can mostly be in "foreign" languages. 

The foreign-language parts could be filtered out from the text that is passed to a backend (before input-limiting). 

One possible library to perform the actual language detection is [pycld3](https://pypi.org/project/pycld3/). It is much faster than [langdetect](https://pypi.org/project/langdetect/), does not require dependencies to be manually installed (installation is using Wheel for Python versions  3.5, 3.6, 3.7, and 3.8), and has Apache 2.0 license. The detected language is given as BCP-47-style language code which is used in Annif too.

The filtering could be optional with a common backend-parameter boolean switch.

**Comment by juhoinkinen** [comment]
Quick runs with a Bonsai model showed that in Finnish test sets line-by-line language filtering (in evaluation only) improved F1@5 scores for [JYX thesis ~1 % point, but worsened for kirjaesittelyt ~2 % points](https://docs.google.com/spreadsheets/d/1sdyXSn_NG2RXfpUHxA4bdNp3ziV9xRb4oDQYlAbUTo0/edit#gid=1956626958&range=A18:O25). Worsening could result from too crude line-by-line filtering (sentence-by-sentence would probably be better), or from the little possibility that Finnish model can learn something from foreign texts (although with lemmatization this seems quite limited).

**Comment by osma** [comment]
> The foreign-language parts could be filtered out from the text that is passed to a backend (before input-limiting).

Sounds good!

> One possible library to perform the actual language detection is pycld3.

+1

> The filtering could be optional with a common backend-parameter boolean switch.

+1

> sentence-by-sentence would probably be better

Agreed - the Analyzer class already has a `tokenize_sentences` method (based on NLTK method `sent_tokenize`) so I think it should be quite easy to rely on that instead of filtering line by line.
