### ISSUE TITLE
STWFSA backend returns duplicate results

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#478]
I set up a stwfsa based project using this configuration adapted from the wiki page of the STWFSA backend:

```
[stw-stwfsa-en]
name=STWFSA STW english
language=en
backend=stwfsa
vocab=stw-en
concept_type_uri=http://zbw.eu/namespaces/zbw-extensions/Descriptor
sub_thesaurus_type_uri=http://zbw.eu/namespaces/zbw-extensions/Thsys
thesaurus_relation_type_uri=http://www.w3.org/2004/02/skos/core#broader
thesaurus_relation_is_specialisation=False
```

Then I trained this with stw-econbiz-small.tsv.gz from the Annif-tutorial stw-zbw data set.

When I use `annif suggest` with text that contains multiple matches for the same term, I get duplicate results:

```
$ echo "economics. economics" | annif suggest stw-stwfsa-en
<http://zbw.eu/stw/descriptor/10032-2>	Economics	0.14664009111617313
<http://zbw.eu/stw/descriptor/10032-2>	Economics	0.14664009111617313
```

This is obviously wrong, since the list of suggestions should not contain duplicates.

Looking at [this PR](https://github.com/zbw/stwfsapy/pull/32) that was quite recently merged to stwfsapy, I think this may already have been fixed upstream. Annif would just need to switch to a newer version of stwfsapy (and such a version must be released first). Ping @mo-fu - do you agree with the analysis? Could this be fixed on the Annif side as well by upgrading stwfsapy?

**Comment by mo-fu** [comment]
Yes, this was recently fixed upstream. I try to get out a release this week. There are additional changes for handling of longer inputs that I want to include.

**Comment by osma** [comment]
Great to hear, thanks @mo-fu!
