### ISSUE TITLE
Attempting to use a private project returns "No projects found with id" from inside command line.

### ISSUE THREAD

**Issue by Hurttaj** [NatLibFi/Annif#521]
Looking at the documentation of the access settings, it seems that the purpose of hidden projects is to hide them from the UI, but still expose them to the API, and the purpose of private projects is to hide them from any REST API entirely, but still make them usable from within the command line.

Instead, making a project private within projects.cfg also makes it unusable from within the command line.

I am running annif following the instructions here: https://github.com/NatLibFi/Annif/wiki/Running-as-a-WSGI-service

**Comment by osma** [comment]
That wiki page may be a bit out of date, unfortunately... Annif is no longer using pipenv to handle dependencies. Though that is not directly related to this issue I think.

Can you provide a minimal example i.e. the contents of your projects.cfg file, the command you used, and the output you got?

**Comment by Hurttaj** [comment]
This is the project I was trying to affect.

```
[ksml-fasttext-new]
name=ksml-fasttext-new
language=fi
backend=fasttext
analyzer=snowball(finnish)
dim=430
lr=0.74
epoch=75
minn=4
maxn=7
minCount=3
loss=hs
limit=1000
chunksize=24
vocab=ksmlvocab
access=private
```

I gave it the command: `annif train ksml-fasttext-new neuwo-annif/ksml-corpus/olddata`
It returned: `No projects found with id 'ksml-fasttext-new'`

This appears to be happening with commands in general. I got the same thing when I was trying to load vocabulary, and changed access to hidden to make it work. I was initially wondering if perhaps I need to do some kind of initialization on the project in a non-private state, but it seems like every command to a private project fails with this same error.

**Comment by osma** [comment]
Thanks for the details! I will see if I can reproduce this.

**Comment by osma** [comment]
Confirmed. There's something wrong with accessing private projects from CLI. The private project shows up in `annif list-projects` output, but commands like `show-project`, `loadvoc` and `train` give the "No projects found with id X" error.

I will try to come up with a fix - I don't expect it to be very difficult now that there's an easy way to trigger it. In the meantime, I suggest that you use `access=hidden` like you already did.

**Comment by osma** [comment]
The fix was simple and has now been committed to the `master` branch. Thank you for reporting!
