### ISSUE TITLE
Update to Optuna 3.x to get rid of deprecation message

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#532]
In recent versions of Annif (which use Optuna 2.8.0), running the `annif hyperopt` command with a `--jobs` parameter gives the following warning:

    FutureWarning: `n_jobs` argument has been deprecated in v2.7.0. This feature will be removed in v4.0.0. See https://github.com/optuna/optuna/releases/tag/v2.7.0.

The Optuna [documentation for the 2.7.0 release](https://github.com/optuna/optuna/releases/tag/v2.7.0) explains that process-based parallelism should be used instead ([tutorial](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html#sphx-glr-tutorial-10-key-features-004-distributed-py)). But that would require a PostgreSQL or MySQL database (SQLite is possible but not recommended).

Another option is to keep using thread-level parallelism using ThreadPoolExecutor instead of the `n_jobs` parameter. That would be easier to implement at least.

**Comment by osma** [comment]
It seems that Optuna has decided to continue supporting the `n_jobs` parameter after all: https://github.com/optuna/optuna/issues/2937
It is also possible that in the future it will become easier to run Optuna in parallel using real multiprocessing: https://github.com/optuna/optuna/issues/2950

Both of these are on the [Optuna version 3 roadmap](https://github.com/optuna/optuna/wiki/Optuna-V3-Roadmap).

So for now I think we should wait and see what happens on the Optuna side.

**Comment by juhoinkinen** [comment]
> In recent versions of Annif (which use Optuna 2.8.0), running the `annif hyperopt` command with a `--jobs` parameter gives the following warning:
> 
> ```
> FutureWarning: `n_jobs` argument has been deprecated in v2.7.0. This feature will be removed in v4.0.0. See https://github.com/optuna/optuna/releases/tag/v2.7.0.
> ```

When updating now to latest Optuna release, i.e. v3.3.0, the above is not shown, but a different one is:
```
FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
```

When just updating to Optuna 3.3.0 unit tests pass. The [migration guide](https://github.com/optuna/optuna/discussions/3930) tells that the (new) method `trial.suggest_float(“x”, low, high)` corresponds to the deprecated method `trial.suggest_uniform(“x”, low, high)`.

**Comment by osma** [comment]
> The https://github.com/optuna/optuna/discussions/3930 tells that the (new) method trial.suggest_float(“x”, low, high) corresponds to the deprecated method trial.suggest_uniform(“x”, low, high).

Okay, let's switch to the new method then! I don't see why it wouldn't work.
