### ISSUE TITLE
Update Commands section in wiki documentation

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#595]
The [Commands](https://github.com/NatLibFi/Annif/wiki/Commands) page in the wiki is getting really out of date and it is missing commands such as `annif index`. I think it needs an overhaul. It would be best to try to generate some of the content automatically from the CLI command help.

Thanks to @cbartz for pointing this out.

**Comment by juhoinkinen** [comment]
These tools seem like they could be used for the task (maybe they were just mentioned by @cbartz):
- [md-click](https://github.com/RiveryIo/md-click)
- [mkdocs-click](https://github.com/DataDog/mkdocs-click)

**Comment by juhoinkinen** [comment]
I hoped [mkdocs-click](https://github.com/DataDog/mkdocs-click) would allow using a custom template for the whole wiki page, but this tool renders the Click commands documentation only to html. Markdown is used only in the template for building the html page. So mkdocs-click is not applicable for this task.

Then I tried [sphinx-click](https://github.com/click-contrib/sphinx-click) plugin for Sphinx with [sphinx-markdown-builder](https://github.com/clayrisser/sphinx-markdown-builder). It can use a Sphinx template in .rst format. Output can look like following:

# Supported CLI commands in Annif

These are the command line commands of Annif, with REST API equivalents when applicable.
Most of these methods take a projectid parameter. Projects are identified by alphanumeric strings (A-Za-z0-9_-).

## annif list-projects

List available projects.

```shell
annif list-projects [OPTIONS]
```

### Options


### -v(, --verbosity( <LVL>)
Either CRITICAL, ERROR, WARNING, INFO or DEBUG


### -p(, --projects( <projects>)
Set path to project configuration file or directory


### -v(, --verbosity( <LVL>)
Either CRITICAL, ERROR, WARNING, INFO or DEBUG

REST equivalent::

```default
GET /projects/
```

## annif show-project

Show information about a project.

```shell
annif show-project [OPTIONS] PROJECT_ID
```

### Options


### -v(, --verbosity( <LVL>)
Either CRITICAL, ERROR, WARNING, INFO or DEBUG


### -p(, --projects( <projects>)
Set path to project configuration file or directory

### Arguments


### PROJECT_ID()
Required argument

REST equivalent::

```default
GET /projects/<projectid>
```


<details>
<summary>The .rst template for above:</summary>

```
===============================
Supported CLI commands in Annif
===============================

These are the command line commands of Annif, with REST API equivalents when applicable.
Most of these methods take a projectid parameter. Projects are identified by alphanumeric strings `(A-Za-z0-9_-)`.

.. click:: annif.cli:run_list_projects
   :prog: annif list-projects

REST equivalent:::

  GET /projects/

.. click:: annif.cli:run_show_project
   :prog: annif show-project

REST equivalent:::

   GET /projects/<projectid>

```

</details>


Unfortunately there are the extra parenthesis following each option and argument, which appear on markdown generation. In normal Sphinx build to html the extra parenthesis are not present.
