### ISSUE TITLE
REST API root resource with version information

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#655]
The Annif REST API currently doesn't have a root resource. A URL such as http://127.0.0.1:5000/v1/ will give a 404 response.

The API could provide a root resource with some basic information about the API service, including the version of Annif, as a JSON object. Something like this:

```json
{ "title": "Annif REST API", "version": "0.60.0" }
```

One fancier way to do this would be to implement the [JSON Home proposal](https://datatracker.ietf.org/doc/html/draft-nottingham-json-home-06). See [this](https://docs.openstack.org/keystone/rocky/user/json_home.html) for a practical example and [this](https://apievangelist.com/2017/08/03/api-discovery-using-json-home/) for some easy to understand examples. But this may be overkill for the purpose of Annif and the JSON Home spec doesn't seem to be widely used.

Elasticsearch also provides information about the API in a root object as JSON. You can see how it looks (without installing it for yourself) in [this](https://community.progress.com/s/article/what-version-of-elasticsearch-do-i-have-installed) post.

The Annif version information, once exposed via the REST API, could be shown in the Finto AI user interface - see https://github.com/NatLibFi/FintoAI/issues/8

**Comment by juhoinkinen** [comment]
Closed by #658.
